### ISSUE TITLE
Error init

### ISSUE THREAD

**Issue by vietnux** [TeamAmaze/LaputaCloudsLib#4]
I has error:

```
Caused by: android.view.InflateException: Binary XML file line #11 in com.amaze.laputacloudslib:layout/activity_main: Binary XML file line #10 in com.amaze.laputacloudslib:layout/content_main: Error inflating class fragment
     Caused by: android.view.InflateException: Binary XML file line #10 in com.amaze.laputacloudslib:layout/content_main: Error inflating class fragment
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property uploadViewModel has not been initialized
        at com.amaze.laputacloudsapp.MainActivity.getUploadViewModel(MainActivity.kt:32)
        at com.amaze.laputacloudsapp.ui.home.HomeFragment.onCreateView(HomeFragment.kt:46)
```

**Comment by EmmanuelMess** [comment]
What did you do to replicate?

**Comment by vietnux** [comment]
@EmmanuelMess  i want using your lib to syn on my cloud

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess i want using your lib to syn on my cloud

I need more info, some code to replicate the issue.

**Comment by vietnux** [comment]
> 
> 
> > @EmmanuelMess i want using your lib to syn on my cloud
> 
> I need more info, some code to replicate the issue.

I haven't added any code yet, I just tried to build your library and it gives me the same error 
It alert in MainActivity.kt
line 32:  "lateinit var uploadViewModel: UploadViewModel"

**Comment by EmmanuelMess** [comment]
Should be fixed now, sorry for the inconvenience.

**Comment by vietnux** [comment]
> 
> 
> Should be fixed now, sorry for the inconvenience.

no problem, i like what you do

**Comment by EmmanuelMess** [comment]
> > Should be fixed now, sorry for the inconvenience.
> 
> no problem, i like what you do

Do tell me if you find any other issues. I've updated quite a bit more things. And do remember this library is missing some features.
